name: Anirban Mitra
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
# added later might need to remove...for scholar cite
plugins:
  #- jekyll-feed
  #- jekyll-seo-tag
  - jekyll-scholar
scholar:
  style: modern-language-association
